name: Publish release
on:
  release:
    types: [released]

jobs:
  publish-release:
    name: Publish release
    uses: logikal-io/github-workflows/.github/workflows/publish-release.yml@v10
    with:
      name: django-logikal
      docs-workload-identity-provider: "projects/1092349290577/locations/global/\
                                        workloadIdentityPools/ci-cd/providers/github-actions"
      docs-uploader-service-account: docs-uploader@docs-logikal-io.iam.gserviceaccount.com
      docs-target-bucket: website-docs-logikal-io
      docs-website-service-url-map: website-docs-logikal-io-service
      docs-https-redirect-url-map: website-docs-logikal-io-https-redirect
    permissions:
      contents: read
      id-token: write
    secrets: inherit
